import React from 'react';

const GeneratedMediaCard = ({ imageUrl }) => {
  const displayImage = imageUrl || "https://images.unsplash.com/photo-1614729939124-032f0b56c9ce?q=80&w=600&auto=format&fit=crop";

  return (
    <div className="bg-white/60 backdrop-blur-md rounded-[2rem] p-3 shadow-sm border border-white/50 w-full max-w-[320px]">
      <div className="w-full h-[180px] rounded-3xl overflow-hidden bg-gradient-to-br from-[#D9D3F6] to-[#EBE9F9]">
        {/* Render generated image */}
        <img 
          src={displayImage} 
          alt="Generated AI Media" 
          className="w-full h-full object-cover mix-blend-multiply opacity-80"
        />
      </div>
      <p className="text-right text-[11px] text-gray-500 font-medium mt-2 px-2">Generated by AI</p>
    </div>
  );
};

export default GeneratedMediaCard;
